"""Standalone TCG price monitoring and Telegram bot module."""

from .bot import (
    BoardLoader,
    CatalogRenderer,
    LookupRenderer,
    PendingTelegramTextClarification,
    PhotoLookupRenderer,
    ReputationRenderer,
    TelegramBotClient,
    TelegramCommandProcessor,
    TelegramFileAttachment,
    TelegramLookupQuery,
    TelegramPhotoQuery,
    TelegramReputationDelivery,
    TelegramReputationQuery,
    TelegramTextIntentOption,
    TelegramTextReplyPlan,
    build_processing_ack,
    default_board_loader,
    default_lookup_renderer,
    default_photo_renderer,
    format_liquidity_board,
    format_photo_lookup_result,
    handle_telegram_message,
    parse_lookup_command,
    parse_reputation_snapshot_command,
    run_telegram_polling,
    send_telegram_test_message,
)
from .commands import build_card_spec, list_reference_sources, lookup_card, seed_example_watchlist
from .formatters import (
    format_jpy,
    format_lookup_result,
    format_lookup_result_telegram,
    format_reference_sources,
    lookup_result_payload,
    lookup_result_to_json,
    reference_sources_payload,
    reference_sources_to_json,
)
from .natural_language import (
    TelegramNaturalLanguageIntent,
    TelegramNaturalLanguageRouter,
    build_telegram_natural_language_router,
    fallback_route_telegram_natural_language,
)

__all__ = [
    # bot
    "BoardLoader",
    "CatalogRenderer",
    "LookupRenderer",
    "PendingTelegramTextClarification",
    "PhotoLookupRenderer",
    "ReputationRenderer",
    "TelegramBotClient",
    "TelegramCommandProcessor",
    "TelegramFileAttachment",
    "TelegramLookupQuery",
    "TelegramPhotoQuery",
    "TelegramReputationDelivery",
    "TelegramReputationQuery",
    "TelegramTextIntentOption",
    "TelegramTextReplyPlan",
    "build_processing_ack",
    "default_board_loader",
    "default_lookup_renderer",
    "default_photo_renderer",
    "format_liquidity_board",
    "format_photo_lookup_result",
    "handle_telegram_message",
    "parse_lookup_command",
    "parse_reputation_snapshot_command",
    "run_telegram_polling",
    "send_telegram_test_message",
    # commands
    "build_card_spec",
    "list_reference_sources",
    "lookup_card",
    "seed_example_watchlist",
    # formatters
    "format_jpy",
    "format_lookup_result",
    "format_lookup_result_telegram",
    "format_reference_sources",
    "lookup_result_payload",
    "lookup_result_to_json",
    "reference_sources_payload",
    "reference_sources_to_json",
    # natural_language
    "TelegramNaturalLanguageIntent",
    "TelegramNaturalLanguageRouter",
    "build_telegram_natural_language_router",
    "fallback_route_telegram_natural_language",
]
